FROM ubuntu:latest

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

#get python3 and pip3
RUN apt-get update && apt-get install -y python3-pip && pip3 install --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip3 install -r requirements.txt

# Make port 8080 available to the world outside this container
EXPOSE 8080

ENTRYPOINT ["python3", "-m", "flask_server"]

